# Yamllint configuration file, used by github actions and commit hooks.
#
# Disables some tests for src/tests/ftest due to existing errors.
# .yamllint is used in preference by the tool and is in .gitignore so can be used locally to
# overrule settings here for local commit hooks.

extends: default

rules:
  line-length:
    max: 100
    level: warning
    ignore: |
      src/tests/ftest/
      src/vos/storage_estimator/
  indentation:
    ignore: src/tests/ftest/
  commas:
    ignore: src/tests/ftest/
  truthy:
    ignore: src/tests/ftest/
  document-start:
    present: false
  document-end:
    present: false
  comments-indentation:
    ignore: src/tests/ftest/
  comments:
    ignore: |
      src/tests/ftest/
      utils/config/

ignore: |
  src/control/vendor/
  .git/
  src/rdb/raft/
  venv
  /build/
  /install/
